nodeLinker: node-modules
supportedArchitectures:
  os:
    - "current"
    - "darwin"
    - "linux"
    - "win32"
  cpu:
    - "current"
    - "x64"
    - "x86"
    - "arm"
    - "ia32"
  libc:
    - "current"
    - "glibc"
    - "musl"
