nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - x86
    - arm
    - ia32
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32
