name: Publish Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: main

      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # needed to use yarn v4
      - name: Enable corepack
        run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: |
          yarn install --immutable --check-cache
          yarn build
          yarn pack

      - name: Publish
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
